name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Build typescript & flow
      run: yarn build

    - name: Run Validation steps including Linting and Unit Tests
      run: yarn validate

  build_android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    - name: Build with Library with Gradle and check lints
      run: cd android;./gradlew build test